INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Cássio');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Fagner');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Gil');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Balbuena');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Fábio Santos');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Fausto Vera');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Du Queiroz');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Renato Augusto');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Yuri Alberto');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Roger Guedes');
INSERT INTO Cliente(id, nome) VALUES (nextval('hibernate_sequence'), 'Giuliano');